/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "Kepler",
            customMemoryMap:
           [          
                ["MSMC_RSVD", 
                     {
                        name: "MSMC_RSVD",
                        base: 0x0c000000,                    
                        len:  0x00100000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["L1DSRAM", 
                     {
                        name: "L1DSRAM",
                        base: 0x00f00000,                    
                        len: 0x00008000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["L1PSRAM", 
                     {
                        name: "L1PSRAM",
                        base: 0x00e00000,                    
                        len: 0x00008000,                    
                        space: "code",
                        access: "RWX",
                     }
                ],
                ["L2SRAM", 
                     {
                        name: "L2SRAM",
                        base: 0x00800000,                    
                        len: 0x00100000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_MSMC_SHARED_HEAP", 
                     {
                        name: "LTE1_MSMC_SHARED_HEAP",
                        base: 0x0C100000,
                        len:  0x000F0000,
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_MSMC_L2DP", 
                     {
                        name: "LTE1_MSMC_L2DP",
                        base: 0x0C1F0000,                    
                        len:  0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_MSMC_L1SLAVE", 
                     {
                        name: "LTE1_MSMC_L1SLAVE",
                        base: 0x0C200000,
                        len:  0x00010000,
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_MSMC_L1MASTER", 
                     {
                        name: "LTE1_MSMC_L1MASTER",
                        base: 0x0C210000,                    
                        len:  0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_MSMC_L2SCHED", 
                     {
                        name: "LTE1_MSMC_L2SCHED",
                        base: 0x0C220000,                    
                        len:  0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_MSMC_SHARED_HEAP", 
                     {
                        name: "LTE2_MSMC_SHARED_HEAP",
                        base: 0x0C230000,
                        len:  0x000F0000,
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_MSMC_L2DP", 
                     {
                        name: "LTE2_MSMC_L2DP",
                        base: 0x0C320000,                    
                        len:  0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_MSMC_L1SLAVE", 
                     {
                        name: "LTE2_MSMC_L1SLAVE",
                        base: 0x0C330000,
                        len:  0x00010000,
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_MSMC_L1MASTER", 
                     {
                        name: "LTE2_MSMC_L1MASTER",
                        base: 0x0C340000,                    
                        len:  0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_MSMC_L2SCHED", 
                     {
                        name: "LTE2_MSMC_L2SCHED",
                        base: 0x0C350000,                    
                        len:  0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3_SYSLIB_ROOT_RSVD_MEM", 
                     {
                        name: "DDR3_SYSLIB_ROOT_RSVD_MEM",
                        base: 0xA0000000,                    
                        len:  0x00010000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3_SYSLIB_RESMGR_RSVD", 
                     {
                        name: "DDR3_SYSLIB_RESMGR_RSVD",
                        base: 0xA0010000,                    
                        len:  0x0000F000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_DDR3_NAME_PROXY_RSVD", 
                     {
                        name: "LTE1_DDR3_NAME_PROXY_RSVD",
                        base: 0xA001F000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_DDR3_NAMED_RESOURCE", 
                     {
                        name: "LTE1_DDR3_NAMED_RESOURCE", 
                        base: 0xA0020000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_DDR3_SHARED_HEAP", 
                     {
                        name: "LTE1_DDR3_SHARED_HEAP",
                        base: 0xA0021000,
                        len:  0x01000000,
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_DDR3_L2DP", 
                     {
                        name: "LTE1_DDR3_L2DP",
                        base: 0xA1021000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_DDR3_L1SLAVE", 
                     {
                        name: "LTE1_DDR3_L1SLAVE",
                        base: 0xA2021000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_DDR3_L1MASTER", 
                     {
                        name: "LTE1_DDR3_L1MASTER",
                        base: 0xA3021000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE1_DDR3_L2SCHED", 
                     {
                        name: "LTE1_DDR3_L2SCHED",
                        base: 0xA4021000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_DDR3_NAME_PROXY_RSVD",
                     {
                        name: "LTE2_DDR3_NAME_PROXY_RSVD",
                        base: 0xB0000000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_DDR3_NAMED_RESOURCE", 
                     {
                        name: "LTE2_DDR3_NAMED_RESOURCE", 
                        base: 0xB0001000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_DDR3_SHARED_HEAP", 
                     {
                        name: "LTE2_DDR3_SHARED_HEAP",
                        base: 0xB0002000,
                        len:  0x01000000,
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_DDR3_L2DP", 
                     {
                        name: "LTE2_DDR3_L2DP",
                        base: 0xB1002000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_DDR3_L1SLAVE", 
                     {
                        name: "LTE2_DDR3_L1SLAVE",
                        base: 0xB2002000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_DDR3_L1MASTER", 
                     {
                        name: "LTE2_DDR3_L1MASTER",
                        base: 0xB3002000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE2_DDR3_L2SCHED", 
                     {
                        name: "LTE2_DDR3_L2SCHED",
                        base: 0xB4002000,                    
                        len:  0x01000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE3_DDR3_NAME_PROXY_RSVD", 
                     {
                        name: "LTE3_DDR3_NAME_PROXY_RSVD",
                        base: 0xB5002000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE3_DDR3_NAMED_RESOURCE", 
                     {
                        name: "LTE3_DDR3_NAMED_RESOURCE", 
                        base: 0xB5003000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE4_DDR3_NAME_PROXY_RSVD", 
                     {
                        name: "LTE4_DDR3_NAME_PROXY_RSVD",
                        base: 0xB5004000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["LTE4_DDR3_NAMED_RESOURCE", 
                     {
                        name: "LTE4_DDR3_NAMED_RESOURCE", 
                        base: 0xB5005000,                    
                        len:  0x00001000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l2Mode: "0k",
          l1PMode: "0k",
          l1DMode: "0k",
    });
    
instance :
    
    override config string codeMemory  = "L2SRAM";   
    override config string dataMemory  = "L2SRAM";                                
    override config string stackMemory = "L2SRAM";

    config String l2Mode = "0k";
    config String l1PMode = "0k";
    config String l1DMode = "0k";
}

